export const MEMBERROLE_SUCCESS = "MEMBERROLE_SUCCESS";
export const MEMBERROLE_FAIL = "MEMBERROLE_FAIL";

export const GET_STEP_SUCCESS = "GET_STEP_SUCCESS";
export const GET_STEP_FAIL = "GET_STEP_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const SEND_REVIEWE_SUCCESS = "SEND_REVIEWE_SUCCESS";
export const SEND_REVIEWE_FAIL = "SEND_REVIEWE_FAIL";

export const MEMBER_SUCCESS = "MEMBER_SUCCESS";
export const MEMBER_FAIL = "MEMBER_FAIL";

export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_FAIL = "COUNTRY_FAIL";

export const COMPANY_SUCCESS = "COMPANY_SUCCESS";
export const COMPANY_FAIL = "COMPANY_FAIL";

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const ADD_PRODUCT_TYPE_SUCCESS = "ADD_PRODUCT_TYPE_SUCCESS";
export const ADD_PRODUCT_TYPE_FAIL = "ADD_PRODUCT_TYPE_FAIL";

export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const TYPEOFPRODUCT_SUCCESS = "TYPEOFPRODUCT_SUCCESS";
export const TYPEOFPRODUCT_FAIL = "TYPEOFPRODUCT_FAIL";

export const CLIENT_SUCCESS = "CLIENT_SUCCESS";
export const CLIENT_FAIL = "CLIENT_FAIL";

export const MANAGE_SUCCESS = "MANAGE_SUCCESS";
export const MANAGE_FAIL = "MANAGE_FAIL";

export const PAYER_SUCCESS = "PAYER_SUCCESS";
export const PAYER_FAIL = "PAYER_FAIL";

export const CLIENTDATA_SUCCESS = "CLIENTDATA_SUCCESS";
export const CLIENTDATA_FAIL = "CLIENTDATA_FAIL";

export const SEND_REVIEWE__SUCCESS = "SEND_REVIEWE__SUCCESS";
export const SEND_REVIEWE__FAIL = "SEND_REVIEWE__FAIL";

export const EXPENSE_SUCCESS = "EXPENSE_SUCCESS";
export const EXPENSE_FAIL = "EXPENSE_FAIL";

export const ONE_EXPENSE_SUCCESS = "ONE_EXPENSE_UCCESS";
export const ONE_EXPENSE_FAIL = "ONE_EXPENSE_FAIL";

export const FACILITIES_SUCCESS = "FACILITIES_SUCCESS";
export const FACILITIES_FAIL = "FACILITIES_FAIL";

export const CHILD_ALL_CATEGORY__FAIL = "CHILD_ALL_CATEGORY__FAIL";
export const CHILD_ALL_CATEGORY_SUCCESS = "CHILD_ALL_CATEGORY_SUCCESS";

export const PRODUCT_ALL_CATEGORY__FAIL = "PRODUCT_ALL_CATEGORY__FAIL";
export const PRODUCT_ALL_CATEGORY_SUCCESS = "PRODUCT_ALL_CATEGORY_SUCCESS";

export const PRODUCT_CATEGORY_SUCCESS = "PRODUCT_CATEGORY_SUCCESS";
export const PRODUCT_CATEGORY__FAIL = "PRODUCT_CATEGORY__FAIL";

export const USER_C_SUCCESS = "USER_C_SUCCESS";
export const USER_C_FAIL = "USER_C_FAIL";

export const MODULE_P_SUCCESS = "MODULE_P_SUCCESS";
export const MODULE_P__FAIL = "MODULE_P__FAIL";

export const INVOICE_QUESTION_SUCCESS = "INVOICE_QUESTION_SUCCESS";
export const INVOICE_QUESTION_FAIL = "INVOICE_QUESTION_FAIL";

export const SEND_INVOICE_SUCCESS = "SEND_INVOICE_SUCCESS";
export const SEND_INVOICE_FAIL = "SEND_INVOICE_FAIL";

export const SEND_INVOICE__SUCCESS = "SEND_INVOICE__SUCCESS";
export const SEND_INVOICE__FAIL = "SEND_INVOICE__FAIL";

export const IMAGE_SUCCESS = "IMAGE_SUCCESS";
export const IMAGE_FAIL = "IMAGE_FAIL";

export const ONE_AUDIT_SUCCESS = "ONE_AUDIT_SUCCESS";
export const ONE_AUDIT_FAIL = "ONE_AUDIT_FAIL";

export const AUDIT_SUCCESS = "AUDIT_SUCCESS";
export const AUDIT_FAIL = "AUDIT_FAIL";

export const QUERY_SUCCESS = "QUERY_SUCCESS";
export const QUERY_FAIL = "QUERY_FAIL";

export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_FAIL = "DASHBOARD_FAIL";
